version: 2
archives:
  - id: pulumi-archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - pulumi-component
builds:
  - binary: pulumi-resource-talos-cluster
    id: pulumi-component
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -w -s -X github.com/spigell/pulumi-talos-cluster/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-talos-cluster/
changelog:
  use: github-native
release:
  disable: false
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'
