# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import builtins
from enum import Enum

__all__ = [
    'MachineTypes',
]


class MachineTypes(builtins.str, Enum):
    """
    Allowed machine types
    """
    CONTROLPLANE = "controlplane"
    WORKER = "worker"
    INIT = "init"
