# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'MachineTypes',
]


@pulumi.type_token("talos-cluster:index:machineTypes")
class MachineTypes(_builtins.str, Enum):
    """
    Allowed machine types
    """
    CONTROLPLANE = "controlplane"
    WORKER = "worker"
    INIT = "init"
