// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TalosCluster
{
    /// <summary>
    /// Initialize a new Talos cluster:
    /// - Creates secrets
    /// - Generates machine configurations for all nodes
    /// </summary>
    [TalosClusterResourceType("talos-cluster:index:Cluster")]
    public partial class Cluster : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Client configuration for bootstrapping and applying resources.
        /// </summary>
        [Output("clientConfiguration")]
        public Output<Outputs.ClientConfiguration> ClientConfiguration { get; private set; } = null!;

        /// <summary>
        /// Generated machine configuration YAML keyed by machine ID.
        /// </summary>
        [Output("generatedConfigurations")]
        public Output<ImmutableDictionary<string, string>> GeneratedConfigurations { get; private set; } = null!;

        /// <summary>
        /// Machine information grouped by machine type.
        /// </summary>
        [Output("machines")]
        public Output<Outputs.ApplyMachines> Machines { get; private set; } = null!;


        /// <summary>
        /// Create a Cluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Cluster(string name, ClusterArgs args, ComponentResourceOptions? options = null)
            : base("talos-cluster:index:Cluster", name, args ?? new ClusterArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/spigell/pulumi-talos-cluster",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ClusterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster endpoint, the Kubernetes API endpoint accessible by all nodes
        /// </summary>
        [Input("clusterEndpoint", required: true)]
        public Input<string> ClusterEndpoint { get; set; } = null!;

        [Input("clusterMachines", required: true)]
        private InputList<Inputs.ClusterMachinesArgs>? _clusterMachines;

        /// <summary>
        /// Configuration settings for machines
        /// </summary>
        public InputList<Inputs.ClusterMachinesArgs> ClusterMachines
        {
            get => _clusterMachines ?? (_clusterMachines = new InputList<Inputs.ClusterMachinesArgs>());
            set => _clusterMachines = value;
        }

        /// <summary>
        /// Name of the cluster
        /// </summary>
        [Input("clusterName", required: true)]
        public string ClusterName { get; set; } = null!;

        /// <summary>
        /// Kubernetes version to install. 
        /// Default is v1.33.0.
        /// </summary>
        [Input("kubernetesVersion")]
        public Input<string>? KubernetesVersion { get; set; }

        /// <summary>
        /// Version of Talos features used for configuration generation. 
        /// Do not confuse this with the talosImage property. 
        /// Used in NewSecrets() and GetConfigurationOutput() resources. 
        /// This property is immutable to prevent version conflicts across provider updates. 
        /// See issue: https://github.com/siderolabs/terraform-provider-talos/issues/168 
        /// The default value is based on gendata.VersionTag, current: v1.11.5.
        /// </summary>
        [Input("talosVersionContract")]
        public Input<string>? TalosVersionContract { get; set; }

        public ClusterArgs()
        {
            KubernetesVersion = "v1.33.0";
            TalosVersionContract = "v1.11.5";
        }
        public static new ClusterArgs Empty => new ClusterArgs();
    }
}
