// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.TalosCluster
{
    /// <summary>
    /// Allowed machine types
    /// </summary>
    [EnumType]
    public readonly struct MachineTypes : IEquatable<MachineTypes>
    {
        private readonly string _value;

        private MachineTypes(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static MachineTypes Controlplane { get; } = new MachineTypes("controlplane");
        public static MachineTypes Worker { get; } = new MachineTypes("worker");
        public static MachineTypes Init { get; } = new MachineTypes("init");

        public static bool operator ==(MachineTypes left, MachineTypes right) => left.Equals(right);
        public static bool operator !=(MachineTypes left, MachineTypes right) => !left.Equals(right);

        public static explicit operator string(MachineTypes value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is MachineTypes other && Equals(other);
        public bool Equals(MachineTypes other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
