// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const MachineTypes = {
    Controlplane: "controlplane",
    Worker: "worker",
    Init: "init",
} as const;

/**
 * Allowed machine types
 */
export type MachineTypes = (typeof MachineTypes)[keyof typeof MachineTypes];
