// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TalosCluster.Outputs
{

    [OutputType]
    public sealed class ApplyMachines
    {
        public readonly ImmutableArray<Outputs.MachineInfo> Controlplane;
        public readonly ImmutableArray<Outputs.MachineInfo> Init;
        public readonly ImmutableArray<Outputs.MachineInfo> Worker;

        [OutputConstructor]
        private ApplyMachines(
            ImmutableArray<Outputs.MachineInfo> controlplane,

            ImmutableArray<Outputs.MachineInfo> init,

            ImmutableArray<Outputs.MachineInfo> worker)
        {
            Controlplane = controlplane;
            Init = init;
            Worker = worker;
        }
    }
}
