// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TalosCluster.Outputs
{

    [OutputType]
    public sealed class ClientConfiguration
    {
        /// <summary>
        /// The Certificate Authority (CA) certificate used to verify connections to the Talos API server.
        /// </summary>
        public readonly string? CaCertificate;
        /// <summary>
        /// The client certificate used to authenticate to the Talos API server.
        /// </summary>
        public readonly string? ClientCertificate;
        /// <summary>
        /// The private key for the client certificate, used for authenticating the client to the Talos API server.
        /// </summary>
        public readonly string? ClientKey;

        [OutputConstructor]
        private ClientConfiguration(
            string? caCertificate,

            string? clientCertificate,

            string? clientKey)
        {
            CaCertificate = caCertificate;
            ClientCertificate = clientCertificate;
            ClientKey = clientKey;
        }
    }
}
