// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TalosCluster.Outputs
{

    [OutputType]
    public sealed class MachineInfo
    {
        /// <summary>
        /// cluster endpoint applied to node
        /// </summary>
        public readonly string? ClusterEndpoint;
        /// <summary>
        /// Configuration settings for machines to apply. 
        /// This can be retrieved from the cluster resource.
        /// </summary>
        public readonly string Configuration;
        /// <summary>
        /// TO DO
        /// </summary>
        public readonly string? KubernetesVersion;
        /// <summary>
        /// ID or name of the machine.
        /// </summary>
        public readonly string MachineId;
        /// <summary>
        /// The IP address of the node where configuration will be applied.
        /// </summary>
        public readonly string NodeIp;
        /// <summary>
        /// TO DO
        /// </summary>
        public readonly string? TalosImage;
        /// <summary>
        /// User-provided machine configuration to apply. 
        /// This can be retrieved from the cluster resource.
        /// </summary>
        public readonly string? UserConfigPatches;

        [OutputConstructor]
        private MachineInfo(
            string? clusterEndpoint,

            string configuration,

            string? kubernetesVersion,

            string machineId,

            string nodeIp,

            string? talosImage,

            string? userConfigPatches)
        {
            ClusterEndpoint = clusterEndpoint;
            Configuration = configuration;
            KubernetesVersion = kubernetesVersion;
            MachineId = machineId;
            NodeIp = nodeIp;
            TalosImage = talosImage;
            UserConfigPatches = userConfigPatches;
        }
    }
}
