name: prepare-pulumi-env
description: "Donwload dependencies and configure runtimes"
inputs:
  runtime:
    description: "Runtime to install"
    required: true
  with-tests:
    description: "Install deps for tests"
    required: false
    default: 'false'
  with-provider:
    description: "Install deps for provider"
    required: false
    default: 'true'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup cache
      uses: runs-on/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Setup Go ✨
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version-file: provider/go.mod
    - name: Setup Node LTS
      uses: actions/setup-node@v3
      with:
        node-version: 20
      if: startsWith(inputs.runtime, 'nodejs')
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: pulumi/pulumictl
    - name: Generate nodejs sdk package
      shell: bash
      run: make install_nodejs_sdk
      if: startsWith(inputs.runtime, 'nodejs')
    - name: Install pulumi cli
      uses: pulumi/actions@v4
      with:
        pulumi-version: v3.171.0
    - name: Downloading GO dependencies (tests)
      shell: bash
      run: go mod download
      working-directory: tests
      if: startsWith(inputs.with-tests, 'true')
    - name: Downloading GO dependencies (provider)
      shell: bash
      run: go mod download
      working-directory: provider
      if: startsWith(inputs.with-provider, 'true')
