// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface ApplyMachinesArgs {
    configuration: pulumi.Input<string>;
    machineId: pulumi.Input<string>;
    node: pulumi.Input<string>;
}

export interface ClientConfigurationArgs {
    caCertificate?: pulumi.Input<string>;
    clientCertificate?: pulumi.Input<string>;
    clientKey?: pulumi.Input<string>;
}

export interface ClusterMachinesArgs {
    configPatches?: pulumi.Input<string>;
    kubernetesVersion: pulumi.Input<string>;
    machineId: pulumi.Input<string>;
    machineType: pulumi.Input<enums.MachineTypes>;
    talosImage: pulumi.Input<string>;
}
