[project]
name = "pulumi-talos-cluster-integration-tests-infra"
version = "0.0.0"
description = "Shared integration test utilities for pulumi-talos-cluster"
requires-python = ">=3.10"
dependencies = [
  "pyyaml==6.0.3",
  "pytest==9.1.1",
  "jsonschema==4.26.0",
  "pulumi==3.267.0",
  "pulumi-hcloud==1.43.0",
  "ruff==0.16.10",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "pkg"}

[tool.setuptools.packages.find]
where = ["pkg"]
include = ["cluster*"]

[[tool.poetry.packages]]
include = "cluster"
from = "pkg"

