// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TalosCluster.Inputs
{

    public sealed class ClusterMachinesArgs : global::Pulumi.ResourceArgs
    {
        [Input("configPatches")]
        private InputList<string>? _configPatches;

        /// <summary>
        /// User-provided machine configuration to apply. 
        /// Must be a valid array of YAML strings. 
        /// For structure, see https://www.talos.dev/latest/reference/configuration/v1alpha1/config/
        /// </summary>
        public InputList<string> ConfigPatches
        {
            get => _configPatches ?? (_configPatches = new InputList<string>());
            set => _configPatches = value;
        }

        /// <summary>
        /// ID or name of the machine.
        /// </summary>
        [Input("machineId", required: true)]
        public string MachineId { get; set; } = null!;

        /// <summary>
        /// Type of the machine.
        /// </summary>
        [Input("machineType", required: true)]
        public Pulumi.TalosCluster.MachineTypes MachineType { get; set; }

        /// <summary>
        /// The IP address of the node where configuration will be applied.
        /// </summary>
        [Input("nodeIp", required: true)]
        public Input<string> NodeIp { get; set; } = null!;

        /// <summary>
        /// Talos OS installation image. 
        /// Used in the `install` configuration and set via CLI. 
        /// The default is generated based on the Talos machinery version, current: ghcr.io/siderolabs/installer:v1.12.0.
        /// </summary>
        [Input("talosImage")]
        public Input<string>? TalosImage { get; set; }

        public ClusterMachinesArgs()
        {
            TalosImage = "ghcr.io/siderolabs/installer:v1.12.0";
        }
        public static new ClusterMachinesArgs Empty => new ClusterMachinesArgs();
    }
}
