// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TalosCluster.Inputs
{

    public sealed class MachineInfoArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// cluster endpoint applied to node
        /// </summary>
        [Input("clusterEndpoint")]
        public Input<string>? ClusterEndpoint { get; set; }

        /// <summary>
        /// Configuration settings for machines to apply. 
        /// This can be retrieved from the cluster resource.
        /// </summary>
        [Input("configuration", required: true)]
        public Input<string> Configuration { get; set; } = null!;

        /// <summary>
        /// TO DO
        /// </summary>
        [Input("kubernetesVersion")]
        public Input<string>? KubernetesVersion { get; set; }

        /// <summary>
        /// ID or name of the machine.
        /// </summary>
        [Input("machineId", required: true)]
        public Input<string> MachineId { get; set; } = null!;

        /// <summary>
        /// The IP address of the node where configuration will be applied.
        /// </summary>
        [Input("nodeIp", required: true)]
        public Input<string> NodeIp { get; set; } = null!;

        /// <summary>
        /// TO DO
        /// </summary>
        [Input("talosImage")]
        public Input<string>? TalosImage { get; set; }

        /// <summary>
        /// User-provided machine configuration to apply. 
        /// This can be retrieved from the cluster resource.
        /// </summary>
        [Input("userConfigPatches")]
        public Input<string>? UserConfigPatches { get; set; }

        public MachineInfoArgs()
        {
        }
        public static new MachineInfoArgs Empty => new MachineInfoArgs();
    }
}
