name: The NPM package uploading

on:
  push:
    tags:
      - '*'

jobs:
  sdk-nodejs-release:
    uses: spigell/my-shared-workflows/.github/workflows/nodejs-package-release.yaml@main
    with:
      package-directory: 'sdk/nodejs/bin'
      build-command: make build_nodejs_sdk
      setup-action: setup-pulumi-env
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
