name: The prebuilt binaries release

on:
  push:
    tags:
      - '*'

jobs:
  component-release:
    uses: spigell/my-shared-workflows/.github/workflows/golang-binary-release.yaml@main
    permissions:
      contents: write
    with:
      setup-action: 'setup-pulumi-env'
      working-directory: provider
      config-path: ../.goreleaser.yaml
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
