name: Build hcloud Image with Packer and Talos

on:
  push:
    paths:
      - .github/workflows/triggers-build-test-images.yaml
      - integration-tests/packer/run-packer.go
      - integration-tests/packer/hcloud-talos.pkr.hcl
  workflow_dispatch:

env:
  TALOS_VERSION: 'v1.11.0'

jobs:
  build-hcloud-image:
    name: Build hcloud image with talos for tests
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Add HashiCorp APT repository and install Packer
      run: |
        # Add the GPG key
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        # Add the repository
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        # Update and install dependencies
        sudo apt-get update && sudo apt-get install -y curl jq packer

    - name: Build Hetzner Cloud image with Packer
      run: |
        # Initialize and build with Packer
        cd integration-tests/packer
        packer init .
        go run ./run-packer.go -var=talos_version=${{ env.TALOS_VERSION }} -template ./hcloud-talos.pkr.hcl
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
